server:
  port: 8080

spring:
  redis:
    host: 192.168.1.102
    port: 6379
    password: root
    timeout: 5000000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 5000
  datasource:
    password: root@123
    username: root
    url: jdbc:mysql://123.207.210.172:3306/soa?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    hikari:
      connection-timeout: 50000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL

logging:
  level:
    root: info


curator:
  #重试次数
  retryCount: 5
  #重试间隔时间
  elapsedTimeMs: 1000
  # zookeeper 地址
  connectString: 192.168.1.102:2181
  # session超时时间
  sessionTimeoutMs: 60000
  # 连接超时时间
  connectionTimeoutMs: 5000
  # 节点名称
  namespace: distributed-lock
